//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3._1Console.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ID_Application { get; set; }
        public decimal Order_Amount { get; set; }
        public bool Is_Paid { get; set; }
        public System.DateTime Data_Registration { get; set; }
        public System.DateTime Data_Of_Completition { get; set; }
        public string Patment_Method { get; set; }
        public int ID_Client { get; set; }
        public int ID_Manager { get; set; }
        public int ID_Configuration { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Configuration Configuration { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
