//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3._1Console.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collector_PC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Collector_PC()
        {
            this.Configuration = new HashSet<Configuration>();
        }
    
        public int ID_Collector_Case { get; set; }
        public string F_Name { get; set; }
        public string L_Name { get; set; }
        public string M_Name { get; set; }
        public string Email { get; set; }
        public string Phone_Number { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Configuration> Configuration { get; set; }
    }
}
