//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3._1Console.Module
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuration()
        {
            this.Application = new HashSet<Application>();
        }
    
        public int ID_Configuration { get; set; }
        public int ID_CPU { get; set; }
        public int ID_GPU { get; set; }
        public int ID_RAM { get; set; }
        public int ID_Motherboard { get; set; }
        public int ID_Cooler { get; set; }
        public int ID_Power_Unit { get; set; }
        public int ID_PC_Case { get; set; }
        public int ID_Collector_PC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Application> Application { get; set; }
        public virtual Collector_PC Collector_PC { get; set; }
        public virtual Cooler Cooler { get; set; }
        public virtual CPU CPU { get; set; }
        public virtual GPU GPU { get; set; }
        public virtual Motherboard Motherboard { get; set; }
        public virtual PC_Case PC_Case { get; set; }
        public virtual Power_Unit Power_Unit { get; set; }
        public virtual RAM RAM { get; set; }
    }
}
