//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR3._1Console.Module
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LibraryEntities : DbContext
    {
        public LibraryEntities()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Application { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Collector_PC> Collector_PC { get; set; }
        public virtual DbSet<Configuration> Configuration { get; set; }
        public virtual DbSet<Cooler> Cooler { get; set; }
        public virtual DbSet<CPU> CPU { get; set; }
        public virtual DbSet<GPU> GPU { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Motherboard> Motherboard { get; set; }
        public virtual DbSet<PC_Case> PC_Case { get; set; }
        public virtual DbSet<Power_Unit> Power_Unit { get; set; }
        public virtual DbSet<RAM> RAM { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
